title: Learn Armenian with Միշել
description: My online study guide for Eastern and Western Armenian
theme: just-the-docs

url: https://hoghayeren.github.io
baseurl: "/armenian-notes"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

  last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"  